<?php
// NexusMC Configuration — generated by installer
define('DB_HOST', 'localhost');
define('DB_NAME', 'nexusmc');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');
define('DB_PREFIX', 'nmc_');

define('APP_URL', 'http://localhost');
define('APP_SECRET', 'CHANGE_ME_RANDOM_SECRET');
define('THEME', 'default');
define('TIMEZONE', 'Europe/Copenhagen');

date_default_timezone_set(TIMEZONE);
