<?php
ob_start();
define('INSTALL_MODE', true);
define('ROOT', dirname(__DIR__));

ini_set('session.cookie_httponly', '1');
session_start();

$step   = (int)($_GET['step'] ?? 1);
$errors = [];

// ---- Requirements check ----
$reqs = [
    'PHP 8.1+'        => version_compare(PHP_VERSION, '8.1', '>='),
    'PDO MySQL'       => extension_loaded('pdo_mysql'),
    'OpenSSL'         => extension_loaded('openssl'),
    'JSON'            => extension_loaded('json'),
    'Config writable' => is_writable(ROOT . '/config') || (mkdir(ROOT . '/config', 0755, true) && is_writable(ROOT . '/config')),
];

// ---- Step 2: DB connection test ----
if ($step === 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $_SESSION['db'] = [
        'host'   => trim($_POST['db_host'] ?? 'localhost'),
        'name'   => trim($_POST['db_name'] ?? ''),
        'user'   => trim($_POST['db_user'] ?? ''),
        'pass'   => $_POST['db_pass'] ?? '',
        'prefix' => preg_replace('/[^a-z0-9_]/i', '', trim($_POST['db_prefix'] ?? 'nmc_')),
    ];
    $_SESSION['app_url'] = rtrim(trim($_POST['app_url'] ?? ''), '/');

    try {
        $pdo = new PDO(
            "mysql:host={$_SESSION['db']['host']};charset=utf8mb4",
            $_SESSION['db']['user'],
            $_SESSION['db']['pass'],
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$_SESSION['db']['name']}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        header('Location: ?step=3');
        exit;
    } catch (PDOException $e) {
        $errors[] = 'Database fejl: ' . $e->getMessage();
    }
}

// ---- Step 3: Admin account + finalize ----
if ($step === 3 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $adminUser  = trim($_POST['admin_username'] ?? '');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = $_POST['admin_password'] ?? '';
    $siteName   = trim($_POST['site_name'] ?? 'NexusMC');

    if (!$adminUser || !$adminEmail || !$adminPass) {
        $errors[] = 'Udfyld alle felter.';
    }
    if (strlen($adminPass) < 8) {
        $errors[] = 'Adgangskode skal mindst være 8 tegn.';
    }

    if (empty($errors)) {
        try {
            $db  = $_SESSION['db'];
            $pdo = new PDO(
                "mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4",
                $db['user'],
                $db['pass'],
                [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
            );

            // Run schema
            $sql = file_get_contents(ROOT . '/database/schema.sql');
            $sql = str_replace('{PREFIX}', $db['prefix'], $sql);
            // Split on semicolons, skip comments and empty lines
            foreach (explode(';', $sql) as $query) {
                $query = trim($query);
                if ($query && !str_starts_with($query, '--')) {
                    $pdo->exec($query);
                }
            }

            // Create admin user
            $pdo->prepare(
                "INSERT INTO `{$db['prefix']}users` (username, email, password, role, created_at, last_seen)
                 VALUES (?, ?, ?, 'admin', NOW(), NOW())"
            )->execute([$adminUser, strtolower($adminEmail), password_hash($adminPass, PASSWORD_BCRYPT)]);

            // Update site name setting
            $pdo->prepare(
                "UPDATE `{$db['prefix']}settings` SET value = ? WHERE `key` = 'site_name'"
            )->execute([$siteName]);

            // Write config file
            $secret = bin2hex(random_bytes(32));
            $config  = "<?php\n";
            $config .= "// NexusMC Configuration — generated by installer\n";
            $config .= "define('DB_HOST',    " . var_export($db['host'],   true) . ");\n";
            $config .= "define('DB_NAME',    " . var_export($db['name'],   true) . ");\n";
            $config .= "define('DB_USER',    " . var_export($db['user'],   true) . ");\n";
            $config .= "define('DB_PASS',    " . var_export($db['pass'],   true) . ");\n";
            $config .= "define('DB_CHARSET', 'utf8mb4');\n";
            $config .= "define('DB_PREFIX',  " . var_export($db['prefix'], true) . ");\n\n";
            $config .= "define('APP_URL',    " . var_export($_SESSION['app_url'] ?? '', true) . ");\n";
            $config .= "define('APP_SECRET', " . var_export($secret, true) . ");\n";
            $config .= "define('THEME',      'default');\n";
            $config .= "define('TIMEZONE',   'Europe/Copenhagen');\n\n";
            $config .= "date_default_timezone_set(TIMEZONE);\n";

            file_put_contents(ROOT . '/config/config.php', $config);

            header('Location: ?step=4');
            exit;
        } catch (Throwable $e) {
            $errors[] = 'Fejl: ' . $e->getMessage();
        }
    }
}
// ---- All logic done, now output HTML ----
?>
<!DOCTYPE html>
<html lang="da" class="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Installer NexusMC</title>
<script src="https://cdn.tailwindcss.com"></script>
<script>tailwind.config={darkMode:'class',theme:{extend:{colors:{brand:{DEFAULT:'#10b981',dark:'#059669'}},fontFamily:{sans:['Inter','system-ui','sans-serif']}}}}</script>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>
  :root{color-scheme:dark;} body{background:#0b0f19;}
  .glass{background:rgba(15,23,42,0.85);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.07);}
  .gradient-brand{background:linear-gradient(135deg,#10b981,#0891b2);}
</style>
</head>
<body class="text-slate-100 font-sans antialiased flex items-center justify-center min-h-screen px-4 py-12">

<div class="w-full max-w-2xl">
  <!-- Header -->
  <div class="text-center mb-10">
    <div class="w-16 h-16 gradient-brand rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-xl">
      <svg class="w-9 h-9 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/></svg>
    </div>
    <h1 class="text-3xl font-extrabold text-white">Installer NexusMC</h1>
    <p class="text-slate-400 mt-2">Opsæt dit Minecraft community-website</p>
  </div>

  <!-- Steps indicator -->
  <div class="flex items-center justify-center gap-2 mb-8">
    <?php foreach ([1 => 'Krav', 2 => 'Database', 3 => 'Admin', 4 => 'Færdig'] as $n => $label): ?>
    <div class="flex items-center gap-2">
      <div class="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold
        <?= $step > $n ? 'bg-brand text-white' : ($step === $n ? 'bg-brand text-white ring-4 ring-brand/25' : 'bg-slate-800 text-slate-500') ?>">
        <?= $step > $n ? '✓' : $n ?>
      </div>
      <span class="text-xs hidden sm:block <?= $step === $n ? 'text-white font-medium' : 'text-slate-500' ?>"><?= $label ?></span>
    </div>
    <?php if ($n < 4): ?><div class="w-8 h-px bg-slate-700"></div><?php endif; ?>
    <?php endforeach; ?>
  </div>

  <!-- Errors -->
  <?php if (!empty($errors)): ?>
  <div class="bg-red-500/10 border border-red-500/20 rounded-xl p-4 mb-5 space-y-1">
    <?php foreach ($errors as $err): ?>
    <p class="text-sm text-red-400 flex items-center gap-2">
      <span class="text-red-500">✕</span><?= htmlspecialchars($err, ENT_QUOTES | ENT_HTML5, 'UTF-8') ?>
    </p>
    <?php endforeach; ?>
  </div>
  <?php endif; ?>

  <!-- STEP 1: Requirements -->
  <?php if ($step === 1): ?>
  <div class="glass rounded-2xl p-7">
    <h2 class="text-xl font-bold text-white mb-5">Systemkrav</h2>
    <div class="space-y-3 mb-6">
      <?php foreach ($reqs as $label => $pass): ?>
      <div class="flex items-center justify-between py-2.5 border-b border-slate-800 last:border-0">
        <span class="text-sm text-slate-300"><?= htmlspecialchars($label) ?></span>
        <?php if ($pass): ?>
        <span class="text-xs bg-emerald-500/15 text-emerald-400 border border-emerald-500/25 px-2.5 py-0.5 rounded-full font-medium">✓ OK</span>
        <?php else: ?>
        <span class="text-xs bg-red-500/15 text-red-400 border border-red-500/25 px-2.5 py-0.5 rounded-full font-medium">✕ Fejl</span>
        <?php endif; ?>
      </div>
      <?php endforeach; ?>
    </div>
    <?php if (!in_array(false, $reqs, true)): ?>
    <a href="?step=2" class="block text-center py-3 bg-brand hover:bg-brand-dark text-white font-semibold rounded-xl transition-colors">
      Fortsæt →
    </a>
    <?php else: ?>
    <p class="text-sm text-red-400 text-center">Ret fejlene ovenfor og opdater siden.</p>
    <?php endif; ?>
  </div>

  <!-- STEP 2: Database -->
  <?php elseif ($step === 2): ?>
  <div class="glass rounded-2xl p-7">
    <h2 class="text-xl font-bold text-white mb-5">Databaseopsætning</h2>
    <form method="POST" action="?step=2" class="space-y-4">
      <div class="grid sm:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Database host</label>
          <input type="text" name="db_host" value="localhost" required
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Database navn</label>
          <input type="text" name="db_name" value="nexusmc" required
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Brugernavn</label>
          <input type="text" name="db_user" required
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Adgangskode</label>
          <input type="password" name="db_pass"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Tabel-præfiks</label>
          <input type="text" name="db_prefix" value="nmc_"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
        <div>
          <label class="block text-sm font-medium text-slate-300 mb-1.5">Site URL</label>
          <input type="url" name="app_url" value="http://<?= htmlspecialchars($_SERVER['HTTP_HOST']) ?>"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
        </div>
      </div>
      <button type="submit" class="w-full py-3 bg-brand hover:bg-brand-dark text-white font-semibold rounded-xl transition-colors mt-2">
        Test forbindelse &amp; fortsæt →
      </button>
    </form>
  </div>

  <!-- STEP 3: Admin account -->
  <?php elseif ($step === 3): ?>
  <div class="glass rounded-2xl p-7">
    <h2 class="text-xl font-bold text-white mb-5">Opret administrator konto</h2>
    <form method="POST" action="?step=3" class="space-y-4">
      <div>
        <label class="block text-sm font-medium text-slate-300 mb-1.5">Site navn</label>
        <input type="text" name="site_name" value="NexusMC" required
               class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-brand transition-colors">
      </div>
      <div class="border-t border-slate-800 pt-4">
        <h3 class="text-sm font-semibold text-slate-400 mb-3">Admin konto</h3>
        <div class="space-y-3">
          <input type="text" name="admin_username" required placeholder="Brugernavn"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-brand transition-colors">
          <input type="email" name="admin_email" required placeholder="Email"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-brand transition-colors">
          <input type="password" name="admin_password" required minlength="8" placeholder="Adgangskode (min. 8 tegn)"
                 class="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-2.5 text-white placeholder-slate-500 focus:outline-none focus:border-brand transition-colors">
        </div>
      </div>
      <button type="submit" class="w-full py-3 bg-brand hover:bg-brand-dark text-white font-semibold rounded-xl transition-colors">
        Fuldfør installation →
      </button>
    </form>
  </div>

  <!-- STEP 4: Done! -->
  <?php elseif ($step === 4): ?>
  <div class="glass rounded-2xl p-10 text-center">
    <div class="w-20 h-20 bg-emerald-500/15 rounded-full flex items-center justify-center mx-auto mb-6">
      <svg class="w-10 h-10 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
    </div>
    <h2 class="text-2xl font-bold text-white mb-3">Installation gennemført! 🎉</h2>
    <p class="text-slate-400 mb-7">NexusMC er nu klar til brug. Log ind med din admin-konto og konfigurer dit site.</p>
    <div class="bg-amber-500/10 border border-amber-500/25 rounded-xl p-3 mb-6 text-amber-400 text-sm">
      ⚠️ Slet eller bloker <code class="bg-slate-800 px-1 rounded">/install/</code> mappen af sikkerhedshensyn.
    </div>
    <a href="../" class="inline-block px-8 py-3 bg-brand hover:bg-brand-dark text-white font-semibold rounded-xl transition-colors shadow-lg shadow-brand/25">
      Gå til dit site →
    </a>
  </div>
  <?php endif; ?>
</div>

</body>
</html>
